#!/bin/sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin

# Flush any existing firewall rules we might have.
iptables -F
iptables -t nat -F
iptables -t mangle -F
iptables -X

# Perform the rewriting.
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 8000
iptables -d doesthisgifcontainananimation.com -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8000
iptables -d www.doesthisgifcontainananimation.com -t nat -A OUTPUT -p tcp --dport 80 -j REDIRECT --to 8000

iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to 8443
iptables -d doesthisgifcontainananimation.com -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8443
iptables -d www.doesthisgifcontainananimation.com -t nat -A OUTPUT -p tcp --dport 443 -j REDIRECT --to 8443
